config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def five_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  private

  def update_posts_counter
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %w[admin].freeze

  ROLES.each do |role_name|
    define_method "#{role_name}?" do
      role == role_name
    end
  end

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      users_url
    else
      super
    end
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @commment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    post_creator = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = post
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to user_post_path(post_creator, post)
    else
      flash.now[:error] = "Error: Couldn't create comment"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id]).destroy
    redirect_to user_post_path(@user, @post)
    @post.decrement!(:comments_counter)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post_creator = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post:)
    if @like.save
      flash[:success] = 'Like created successfully'
    else
      flash[:error] = 'Like not created'
    end
    redirect_to user_post_path(post_creator, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    current_user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.user = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = "Error: Couldn't create post"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:id], user_id: params[:user_id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id]).destroy
    @user.decrement!(:posts_counter)
    redirect_to user_path(@user)
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
  <div >
    <h1>Add Comment</h1><br>
  </div>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>

  <div >
    <%= form.label :text %><br>
    <%= form.text_area :text, rows: 5 %>
  </div>
  <div >
       <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p style="color: green" class="notice"><%= notice %></p>
       <p style="color: red" class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render partial: "shared/user", locals: {user: @user } %>

<h3>All posts for <%= @user.name %></h3>
<% @posts.each_with_index do |post, i| %>
    <%= render 'shared/post', post: post, index: i%>

     <div class='div-comments'>
    <% post.five_recent_comments.each_with_index do |comment, index| %>
       <div class='comments'>
          <span style="font-weight :bold font-size: 10px"><%= comment.user.name %>: <%= comment.text %></span>
        </div>
    <% end %>        
    </div>

<% end %>



<div class='user_button'>
  <button>
    <%= link_to 'Pagination', user_post_path(@user, @posts[0]) %>
  </button>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
    <% if @post.errors.any? %>
<div style="color: red">
    <% @post.errors.full_messages.each do |message| %>
        <div> <%= message %> </div>
    <% end %>
</div>
<% end%>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, rows: "5" %>
    </div>

   <%= form.submit "Add Post" %>
<% end %>

app/views/posts/show.html.erb
<h2>Single post</h2>
<div class="post_header">
  <div class="post-show-header">
    <div class="ps-name">
      Post by <%= @user.name %>
    </div>
    <div class="ps-counters">
      Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %>
    </div>
    <% if can? :destroy, @post %>
          <%= button_to "Delete Post", user_post_path(@user, @post), method: :delete %>
    <% end %>
  </div>

  <p><%= @post.title %></p>
  <p><%= @post.text %></p>  
  <div class="flex-clicks">
  <%= button_to 'click to like post', user_post_likes_path(@user, @post), method: 'post' %>
  </div>
</div>

<div class='div-comments'>
  <% @post.five_recent_comments.each do |comment| %>
     <div class='comments'>
      <div>
        <span style="font-weight :bold font-size: 10px"><%= comment.user.name %>:</span> <%= comment.text %>
      </div>
      <div>
        <% if can? :destroy, comment %>
            <%= button_to 'Remove Comment', user_post_comment_path(@post.user, @post, comment), class: 'comment-btn', :method => :delete %>
        <% end %>
      </div>
      </div>
  <% end %>        
</div>

app/views/shared/_post.html.erb
<div class="post_header">

 <div class="ps-name">
    Post #<%= index + 1 %> 
  </div>
  <p class='ps-title'><%= link_to post.title, user_post_path(@user, post) %></p>
  <p><%= post.text %></p>
  <div class="ps-counters1">
    Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %>
  </div>
</div>

app/views/shared/_user.html.erb
<div class='user_box' >
  <div class='user_photo'>        

 <%= image_tag( 'https://icons.iconarchive.com/icons/iconsmind/outline/512/User-icon.png', size: "50x50", :alt => 'User: ' + user.name.to_s  ) -%> 
  </div>
  <div class='user_namePost'>
      <div class='user_name'>
        <h1><%= link_to user.name, user%></h1>
      </div>
        <div class="user_numOfPosts"
      <p>Number of posts: <%= user.posts_counter %></p>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>


<% @users.each_with_index do |user, i| %>
    <%= render 'shared/user', user: user%>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/user', user: @user%>

<div class='user_bio' >
  <b>Bio</b>
  <div>
    <p><%= @user.bio %></p>
  </div>
</div>


<% @user.three_recent_posts.each_with_index do |post, index| %>
  <%= render partial: "shared/post", locals: {post: post, index: index } %>  
<% end %>



<% if false %>
<% end %>